language: node_js

node_js:
  - "6"

sudo: false

matrix:
  fast_finish: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  # Export yarn and node binary paths
  - export PATH=$HOME/.yarn/bin:./node_modules/.bin/:$PATH

install: yarn install

script: npm test

cache:
  directories:
    - $HOME/.npm
    - node_modules
