language: node_js

node_js:
  - "6"

sudo: true # for yarn install

matrix:
  fast_finish: true

before_install:
  - test -d ~/.yarn || sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - test -d ~/.yarn || echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - test -d ~/.yarn || sudo apt-get update -qq
  - test -d ~/.yarn || sudo apt-get install -y -qq yarn
  - export PATH=$HOME/.yarn/bin:./node_modules/.bin/:$PATH

install: yarn install

script: npm test

cache:
  directories:
    - $HOME/.yarn
    - $HOME/.npm
    - node_modules
